export const lang = {
  en: {
    gptSearchBtnText: "GPT Search",
    goHome: "Home",
    signOutText: "Sign Out",
    gptPlaceHolderText: "what would you likes to watch?",
    search: "Search",
    playNowBtn: "Play Now",
    moreInfoBtn: "More info",
    movieCategoriesTitle: {
      nowPlaying: "Now Playing",
      topRated: "Top Rated",
      popular: "Popular",
      upComing: "Upcoming",
    },
    signIn:"Sign In",
    signUp:"Sign Up",
    userIdPlaceHolder:"Email or phone number",
    password:"Password",
    newToNetflix:"New to Netflix? ",
    now:" now",
    fullName:"Full Name",
    alreadyMember:"Already a member?"
  },
  de: {
    gptSearchBtnText: "GPT-Suche",
    goHome: "Heim",
    signOutText: "Abmelden",
    gptPlaceHolderText: "Was würdest du gerne sehen?",
    search: "Suchen",
    playNowBtn: "jetzt spielen",
    moreInfoBtn: "Mehr Info",
    movieCategoriesTitle: {
      nowPlaying: "Läuft gerade",
      topRated: "Bestbewertet",
      popular: "Beliebt",
      upComing: "Bevorstehende",
    },
    signIn:"Anmelden",
    signUp:"Registrieren",
    userIdPlaceHolder:"E-Mail oder Telefonnummer",
    password:"Passwort",
    newToNetflix:"Neu bei Netflix? ",
    now:" Jetzt",
    fullName:"vollständiger Name",
    alreadyMember:"Schon ein Mitglied?"
  },
  fr: {
    gptSearchBtnText: "recherche GPT",
    goHome: "Maison",
    signOutText: "Se déconnecter",
    gptPlaceHolderText: "qu'aimeriez-vous regarder ?",
    search: "Recherche",
    playNowBtn: "joue maintenant",
    moreInfoBtn: "Plus d'informations",
    movieCategoriesTitle: {
      nowPlaying: "Lecture en cours",
      topRated: "Les mieux notés",
      popular: "Populaire",
      upComing: "A venir",
    },
    signIn:"Se connecter",
    signUp:"S'inscrire",
    userIdPlaceHolder:"Email ou numéro de téléphone",
    password:"Mot de passe",
    newToNetflix:"Nouveau sur Netflix ? ",
    now:" maintenant",
    fullName:"nom et prénom",
    alreadyMember:"Déjà membre?"
  },
};
